export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_THEATRES = "FETCH_THEATRES";
export const FETCH_SHOWTIMES = "FETCH_SHOWTIMES";
export const FETCH_TOWNS = "FETCH_TOWNS";